### ISSUE TITLE
conflicting tags materialised for Protoquill in scala 3.3.0-RC6

### ISSUE THREAD

**Issue by bishabosha** [zio/izumi-reflect#391] opened 2023-05-19 19:11 UTC
see https://github.com/zio/zio/issues/8130 (I was asked to reopen here), and https://github.com/softwaremill/realworld-tapir-zio/issues/107

**Comment by pshirshov** [comment] 2023-05-19 23:16
This is actually strange, A[=B] must be a subtype of A[+B], I guess the representation does not _represent_ what's actually wrong there. 
We will have a look.

**Comment by pshirshov** [comment] 2023-05-19 23:16
@bishabosha : could you make a minimal isolated repro please?

**Comment by neko-kai** [comment] 2023-05-19 23:55
@bishabosha 
This is caused by a change/regression in one of the latest Scala 3.3 commits, `HKTypeLambda#declaredVariances` (private API used [here](https://github.com/zio/izumi-reflect/blob/f5156717ebd0eacabcab9b7a08a7f1fbda64d6fd/izumi-reflect/izumi-reflect/src/main/scala-3/izumi/reflect/dottyreflection/Inspector.scala#L80) - there's no public way to get variance of type parameters) is not returning the correct variance for some reason, causing all tags to be generated as invariant.

This change happened somewhere between the latest RC6 and scala-3.3.1-RC1-bin-20230331-7262437-NIGHTLY which is a tested version that doesn't appear to have this problem.

@pshirshov 
> This is actually strange, A[=B] must be a subtype of A[+B], I guess the representation does not represent what's actually wrong there.

It's a subtype, but not equal wrt `equals`/`=:=` and also not equal as a binary string, so them not being exactly the same is probably triggering that failure.

**Comment by pshirshov** [comment] 2023-05-20 00:02
I guess that should be immediately reported...

**Comment by neko-kai** [comment] 2023-05-20 00:03
@bishabosha 
No need for a repro, since this reproduces with just `Tag[List[Int]]` on 3.3.0-RC6, but also I'm not exactly sure this can be fixed on our side. I would expect either `declaredVariances` to have kept working or another API to replace it. (There is a ticket for a public API - https://github.com/lampepfl/dotty/issues/16734)

**Comment by pshirshov** [comment] 2023-05-20 00:05
I'm wondering why did this happen. Isn't our IR included into the community build?

**Comment by bishabosha** [comment] 2023-05-20 00:40
> I'm wondering why did this happen. Isn't our IR included into the community build?

the last update to that was 2021 (the one that's a git submodule)

**Comment by neko-kai** [comment] 2023-05-20 00:49
@bishabosha 
Is there an expectation for us to send PRs to update the version in community build to keep it up to date? We're also in VirtusLab's community build, but that couldn't detect this change because they don't run the tests in that build - compilation succeeds in this case.

**Comment by bishabosha** [comment] 2023-05-20 08:44
> Is there an expectation for us to send PRs to update the version in community build to keep it up to date?

We don't have any process for keeping the dotty community-build projects up to date - so any help from the original maintainers is appreciated.

I would guess the reason is that a lot of these projects were ad-hoc forks made before the projects themselves had migrated to scala 3, now that they are publishing for scala 3 theoretically its less effort.

**Comment by bishabosha** [comment] 2023-05-22 07:58
Is this something that can be "worked around" by having less powerful type lambdas? otherwise this should probably be escalated as a dotty bug even though you relied on non-public api

**Comment by bishabosha** [comment] 2023-05-22 23:40
@neko-kai does this help? https://github.com/lampepfl/dotty/pull/17554 - it seems that variances should be computed by inspecting occurrences of the type parameters in the hk lambda's structure

**Comment by neko-kai** [comment] 2023-05-23 13:00
@bishabosha I'll try that

**Closed as completed** 2023-05-30 00:25 UTC

**Comment by neko-kai** [comment] 2023-05-30 00:32
@adamgfraser I'd recommend to release a new ZIO version with update to izumi-reflect 2.3.8 to avoid users getting hit by this regression if they update to Scala 3.3.0

https://github.com/zio/izumi-reflect/releases/tag/v2.3.8

**Comment by adamgfraser** [comment] 2023-05-30 00:33
@neko-kai Will do!
